### ISSUE TITLE
composer does'nt work

### ISSUE THREAD

**Issue by oitsuki** [DansMaCulotte/colissimo-php#1]
Composer require dansmaculotte/colissimo-php

In InitCommand.php line 726:
                                                                               
  Could not find a version of package dansmaculotte/colissimo-php matching yo  
  ur minimum-stability (stable). Require it with an explicit version constrai  
  nt allowing its desired stability.

**Comment by gaelreyrol** [comment]
There is actually no stable version of this package, use
```bash
composer require dansmaculotte/colissimo-php:dev-master
```

**Comment by oitsuki** [comment]
Ok tk, works.
